sudo: false
language: java
jdk:
  - oraclejdk8
env:
  global:
    - MAVEN_OPTS="-Dskip.web.build=true"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B
